[project]
name = "emerald_service"
version = "0.1.0"
description = "Emerald Routing Service Sample"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.109.0",
    "uvicorn>=0.27.0",
    "boto3>=1.34.0",
    "pytest>=7.0",
    "pydantic>=2.6.0"
]